---
title: "Intro"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


## Installation and setup

```{r setup}
library(roleR)
set.seed(1)
```

## Components of a roleModel workflow



## Basic workflow

```{r}

# set-up parameters
p <- roleParams(
  individuals_local = 1000,
  individuals_meta = 10000,
  species_meta = 50,
  speciation_local = 0.5,
  speciation_meta = 1,
  extinction_meta = 0.8,
  trait_sigma = 2,
  env_sigma = 1,
  comp_sigma = 1,
  dispersal_prob = 0.5,
  mutation_rate = 0.01,
  equilib_escape = 1,
  num_basepairs = 250,
  init_type = 'oceanic_island',
  niter = 1000,
  niterTimestep = 100
)

# initialize the model
m <- roleModel(p)

# run the model
m <- runRole(m)

# get results
getSumStats(m, list(rich = richness, hill = hillAbund))
```

## Setting parameters

## Initializing a roleModel

## Running a roleModel

## RoLE Experiments

## Calculating summary statistics

## Analyzing output (machine learning?)
