install.packages("devtools")
install.packages("usethis")
library(devtools)
install.packages("glue")
install.packages("lifecycle")
install.packages("rlang")
install.packages("magrittr")
install.packages("purrr")
install.packages("cli")
install.packages("ellipsis")
install.packages("crayon")
devtools::install_github('scrm/scrm-r')
devtools::install_github("ajrominger/pika")

install.packages("Rcpp")
install.packages("TreeSim")
install.packages("RcppArmadillo")
