// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_birthCpp();
RcppExport SEXP _rcpp_module_boot_deathCpp();
RcppExport SEXP _rcpp_module_boot_immigrationCpp();
RcppExport SEXP _rcpp_module_boot_iterSimCpp();
RcppExport SEXP _rcpp_module_boot_commCpp();
RcppExport SEXP _rcpp_module_boot_phyloCpp();
RcppExport SEXP _rcpp_module_boot_modelCpp();
RcppExport SEXP _rcpp_module_boot_paramsCpp();
RcppExport SEXP _rcpp_module_boot_paramValuesCpp();
RcppExport SEXP _rcpp_module_boot_speciationCpp();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_birthCpp", (DL_FUNC) &_rcpp_module_boot_birthCpp, 0},
    {"_rcpp_module_boot_deathCpp", (DL_FUNC) &_rcpp_module_boot_deathCpp, 0},
    {"_rcpp_module_boot_immigrationCpp", (DL_FUNC) &_rcpp_module_boot_immigrationCpp, 0},
    {"_rcpp_module_boot_iterSimCpp", (DL_FUNC) &_rcpp_module_boot_iterSimCpp, 0},
    {"_rcpp_module_boot_commCpp", (DL_FUNC) &_rcpp_module_boot_commCpp, 0},
    {"_rcpp_module_boot_phyloCpp", (DL_FUNC) &_rcpp_module_boot_phyloCpp, 0},
    {"_rcpp_module_boot_modelCpp", (DL_FUNC) &_rcpp_module_boot_modelCpp, 0},
    {"_rcpp_module_boot_paramsCpp", (DL_FUNC) &_rcpp_module_boot_paramsCpp, 0},
    {"_rcpp_module_boot_paramValuesCpp", (DL_FUNC) &_rcpp_module_boot_paramValuesCpp, 0},
    {"_rcpp_module_boot_speciationCpp", (DL_FUNC) &_rcpp_module_boot_speciationCpp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_roleR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
