# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compMatCalcTest <- function(x, sigC) {
    .Call(`_roleR_compMatCalcTest`, x, sigC)
}

envDistCalcTest <- function(x, envOptim, sigE) {
    .Call(`_roleR_envDistCalcTest`, x, envOptim, sigE)
}

s4FromRcpp <- function(x) {
    .Call(`_roleR_s4FromRcpp`, x)
}

testUpdatePhylo <- function(tre, i, scale) {
    .Call(`_roleR_testUpdatePhylo`, tre, i, scale)
}

simRole <- function(x, p) {
    .Call(`_roleR_simRole`, x, p)
}

