# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name iterSimCpp
#' @title a C++ function to iterate the RoLE model through nstep steps of simulation
#' @param model the entire C++ model, an object of class roleModelCpp
#' @param nstep the number of steps to iterate
NULL

#' @name specLocal
#' @title function to implement speciation for \code{localComm} class objects
#' @param x an object of class \code{localComm}
#' @param i the index to undergo speciation
#' @param p the roleModel params
NULL

