#' @title Run a `roleModel` or `roleExperiment`
#' 
#' @description `runRole` takes a `role*` object and simulates all processes 
#'     specified in the given parameters
#' 
#' @param x `roleModel` or `roleExperiment` object to run
#' @param cores number of cores
#' @return `roleModel` or `roleExperiment` run for the specified number of time
#'     steps
#' 
#' @details Prior to invoking `runRole`, the `role*` input object must be 
#'     initialized with a set of parameters, e.g., as generated by `roleParams`.
#' 
#' @examples 
#' # create and run a model
#' model <- roleModel(roleParams())
#' model <- runRole(model)
#' 
#' # create and run an experiment
#' p1 <- roleParams(dispersal_prob = 0.2)
#' p2 <- roleParams(dispersal_prob = 0.3)
#' p3 <- roleParams(dispersal_prob = 0.4)
#' exp <- roleExperiment(list(p1,p2,p3))
#' exp <- runRole(exp)
#' @rdname runRole
#' @export

setGeneric('runRole', 
           def = function(x, cores=1) standardGeneric('runRole'), 
           signature = 'x')


#' runRole on roleModel
#' @name runRole
#' @aliases runRole,roleModel-method
#' @docType methods
#' @rdname runRole
setMethod('runRole', 
          signature = 'roleModel', 
          definition = function(x) {
              # augment the data in the model based on the params
              m <- bufferModelData(x)
              
              m@modelSteps[[1]]@localComm@spLastOriginGen
              # returns the new modelSteps (a list of roleData)
              m@modelSteps <- simRole(m@modelSteps[[1]], m@params)

              # trim buffer from species-level vectors down to actual sMax
              m <- trimModelData(m)

              # browser()
              # add popgen
              m <- runmsprim(m)
              
              return(m)
          }
)


#' runRole on roleExperiment
#' @name runRole
#' @aliases runRole,roleExperiment-method
#' @docType methods
#' @rdname runRole

setMethod('runRole', 
          signature = 'roleExperiment', 
          definition = function(x, cores = 1) {
              oldInits <- x@inits
              
              # run constituent models
              if(cores == 1){
                  modList <- lapply(x@inits, runRole)
                  simRole()
              } else {
                  modList <- parallel::parLapplyLB(X = 1, fun = function(i) {
                      i
                  })
              }
              
              # convert list of models to list of experiments
              expList <- lapply(modList, as, Class = 'roleExperiment')
              
              # combine list
              x <- Reduce(rbind2, expList)
              
              # add back the original inits
              x@inits <- oldInits
              
              return(x)
          }
)

# trim model data
# trim the buffer zeros from species-level vectors in each modelStep down to
# the actual species count (sMax) recorded in the phylo@n of the final step
# @param model roleModel object returned by simRole
trimModelData <- function(model) {
    nspp <- model@modelSteps[[length(model@modelSteps)]]@phylo@n

    model@modelSteps <- lapply(model@modelSteps, function(step) {
        step@localComm@spAbund <- step@localComm@spAbund[1:nspp]
        step@localComm@spAbundHarmMean <- step@localComm@spAbundHarmMean[1:nspp]
        step@localComm@spPropHarmMean <- step@localComm@spPropHarmMean[1:nspp]
        step@localComm@spLastOriginStep <- step@localComm@spLastOriginStep[1:nspp]
        step@localComm@spLastOriginGen <- step@localComm@spLastOriginGen[1:nspp]
        step@localComm@spGenDiv <- step@localComm@spGenDiv[1:nspp]
        step@localComm@spTajD <- step@localComm@spTajD[1:nspp]
        step
    })

    return(model)
}


# buffer model data
# augment the data of the not-yet-run model based on what is expected from the
# params called right before the model is run in Cpp
# @param model model

bufferModelData <- function(model) {
    p <- model@params
    
    # calculate absolute max number of new species (each iter is speciation)
    expec_n_spec <- p@niter
    el_add <- (expec_n_spec * 2 - 1) + 1
    at_add <- expec_n_spec + 1
    
    # buffer phylo ----
    
    # edges get -1s
    model@modelSteps[[1]]@phylo@e <- rbind(model@modelSteps[[1]]@phylo@e,
                                           matrix(-1, nrow = el_add, ncol = 2))
    
    # lengths get 0s
    model@modelSteps[[1]]@phylo@l <- c(model@modelSteps[[1]]@phylo@l,
                                       rep(0, el_add))
    
    # alives get FALSE
    model@modelSteps[[1]]@phylo@alive <- c(model@modelSteps[[1]]@phylo@alive,
                                           rep(FALSE, at_add))
    
    # tipNames get 'local_speciation_j'
    model@modelSteps[[1]]@phylo@tipNames <-
        c(model@modelSteps[[1]]@phylo@tipNames,
          paste0('local_speciation_', 1:at_add))
    
    # calc buffer size for local species vects
    local_add <- p@species_meta + expec_n_spec
    local_add <- local_add - length(model@modelSteps[[1]]@localComm@spAbund)
    
    
    # buffer local species vectors with 0s
    zeroAdd <- rep(0, local_add)
    
    model@modelSteps[[1]]@localComm@spLastOriginStep <-
        c(model@modelSteps[[1]]@localComm@spLastOriginStep, zeroAdd)
    
    model@modelSteps[[1]]@localComm@spLastOriginGen <-
        c(model@modelSteps[[1]]@localComm@spLastOriginGen, zeroAdd)
    
    model@modelSteps[[1]]@localComm@spAbund <-
        c(model@modelSteps[[1]]@localComm@spAbund, zeroAdd)
    
    model@modelSteps[[1]]@localComm@spAbundHarmMean <-
        c(model@modelSteps[[1]]@localComm@spAbundHarmMean, zeroAdd)
    
    model@modelSteps[[1]]@localComm@spPropHarmMean <-
        c(model@modelSteps[[1]]@localComm@spPropHarmMean, zeroAdd)
    
    return(model)
}

# getValuesFromParams
# @description
# run iter functions over params to generate a new object of class paramValues 
# that contains ONLY vectors of values and no functions
# @param p an object of class `roleParams`
# @param i the iterations over which to calculate parameter values
# @return a list of parameter vectors, each equal in length to `length(i)`

getValuesFromParams <- function(p, i) {
    # slot names
    s <- methods::slotNames(p)
    
    # apply over slots
    pvals <- lapply(s, function(x) {
        thisP <- methods::slot(p, x)
        
        if(inherits(thisP, 'function')) {
            return(thisP(i))
        } else {
            return(rep(thisP, length(i)))
        }
    })
    
    names(pvals) <- s
    
    return(pvals)
}

# helper function that takes a roleModel object and preps the data therein 
# for input int msprime, then runs msprime on those inputs, finally returns
# the model object with updated pop gen info

runmsprim <- function(m) {
    # number of temporal snapshots
    ntshot <- length(m@modelSteps)
    
    finalPhylo <- m@modelSteps[[ntshot]]@phylo
    
    nspp <- finalPhylo@n
    
    # time by spp matrix with abundances in cells
    tBySpp <- mkTBySpp(l = m@modelSteps, sname = "spAbund", 
                       nspp = nspp)
    
    # matrix of same format but with harmonic mean abunds in cells
    tByHmean <- mkTBySpp(l = m@modelSteps, sname = "spAbundHarmMean", 
                         nspp = nspp)
    
    # matrix of same format but with divergence times in cells
    tdiv <- mkTBySpp(l = m@modelSteps, sname = "spLastOriginGen", 
                     nspp = nspp)
    
    # meta abunds
    metaAbund <- round(m@modelSteps[[1]]@metaComm@spAbund * 
                           m@info$individuals_meta[1])
    
    # meta tree needs to modified to have tip labels corresponding to spp IDs
    # but preceded by a character cause msprime canʻt make populations with 
    # number names
    tre <- as(finalPhylo, "phylo")
    tre$tip.label <- paste0("t", 1:nspp)
    nwk <- ape::write.tree(tre, digits = 18)
    
    # time in generations of each snapshot
    gens <- m@info$generations
    
    # harmonic mean of local community size
    Jharm <- m@params@individuals_local(1:m@params@niter)
    Jharm <- length(Jharm) / sum(1 / Jharm)
    
    # python ----
    
    # path to the python file
    pyfi <- system.file("python", "role_msprime.py", 
                        package = "roleR")
    
    reticulate::source_python(pyfi)
    
    res <- sim_role(Jm = m@params@individuals_meta, 
                    curtime = max(gens), 
                    nwk = nwk, 
                    meta_abund = metaAbund, 
                    local_sad = tBySpp, 
                    local_hm = tByHmean,  
                    J_harm = Jharm,  
                    gens = gens, 
                    tdiv = tdiv, 
                    alpha = m@params@alpha(1), 
                    m = m@params@dispersal_prob(1), 
                    sequence_length = m@params@num_basepairs, 
                    mu = m@params@mutation_rate)
    
    # msprime output as list of R data.frames
    # res[[1]] is data.frame of sequences per individual
    # res[[2]] is data.frame of pop gen sum stats per spp
    res <- reticulate::py_to_r(res)
    
    # split by time, because need to match time and modelSteps
    indDat <- split(res[[1]], res[[1]]$time)
    sppDat <- split(res[[2]], res[[2]]$time)
    
    for(i in 1:ntshot) {
        thisGen <- m@info$generations[i]
        
        theseIndDat <- indDat[[as.character(thisGen)]]
        theseSppDat <- sppDat[[as.character(thisGen)]]
        
        # species IDs from roleModel object
        theseID <- m@modelSteps[[i]]@localComm@indSpecies
        
        # add sorted sequence data to model output
        m@modelSteps[[i]]@localComm@indSeqs <- mergeSpp(theseIndDat, theseID)
        
        # sort spp level data
        theseSppDat <- theseSppDat[order(theseSppDat$sp_id), ]
        
        # add sorted gen div data
        m@modelSteps[[i]]@localComm@spGenDiv <- theseSppDat$pi
        
        # add sorted tajima d data (no slot so won't work right now)
        # m@modelSteps[[i]]@localComm@spTajD <- theseSppDat$tajimas_D
        
    }
    
    return(m)
}


# function to make time by spp matrix from list of roleData snapshots by
# specifying which slot we want to use to populate the cells
# returns a data.frame with spp IDs as colnames
mkTBySpp <- function(l, sname, nspp) {
    tbs <- lapply(l, function(d) {
        slot(d@localComm, sname)
    })
    tbs <- do.call(rbind, tbs)
    
    tbs <- as.data.frame(tbs)
    names(tbs) <- as.character(1:nspp)
    
    return(tbs)
}


# function to match spp IDs and merge data when there are duplicate IDs
mergeSpp <- function(pyDat, sppID) {
    # browser()
    # vectors to count the occurrences of each ID
    sppIDCounter <- ave(seq_along(sppID), sppID, FUN = seq_along)
    pyCounter <- ave(seq_len(nrow(pyDat)), pyDat$sp_id, FUN = seq_along)
    
    # unique keys for matching purposes
    sppIDKey <- paste(sppID, sppIDCounter, sep = "_")
    pyKey <- paste(pyDat$sp_id, pyCounter, sep = "_")
    
    ii <- match(sppIDKey, pyKey)
    
    return(pyDat$seq_alignment[ii])
}
